name: Build and Deploy Production

on:
  workflow_dispatch:

run-name: >
  ${
    startsWith(github.ref, 'refs/tags/v') && (
      contains(github.ref_name, '-hotfix') || matches(github.ref_name, '^v[0-9]+\.[0-9]+$')
    ) && format('[RELEASE][PRODUCTION] {0}', github.ref_name)
    || format('[RELEASE][PRODUCTION] {0}', github.event.head_commit.message)
  }

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Next.js Project
        uses: ./.github/actions/setup-nextjs

  build-deploy-production:
    needs: setup
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Deploy Production
        uses: ./.github/actions/build-and-deploy-nextjs
        with:
          stage: release
          service: corporate-travel-web

  build-deploy-demo:
    needs: setup
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Deploy Demo
        uses: ./.github/actions/build-and-deploy-nextjs
        with:
          stage: demo
          service: corporate-travel-demo-web
