name: Build and Deploy Production

on:
  push:
    tags:
      - "v*.*"
      - "v*.*-hotfix.*"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Next.js Project
        uses: ./.github/actions/setup-nextjs

  build-deploy-production:
    needs: setup
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Build and Deploy Production
        uses: ./.github/actions/build-deploy-nextjs
        with:
          stage: release
          service: corporate-travel-web

  build-deploy-demo:
    needs: setup
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - name: Build and Deploy Demo
        uses: ./.github/actions/build-deploy-nextjs
        with:
          stage: demo
          service: corporate-travel-demo-web
