name: Build and Deploy Test

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      run_title:
        description: 'Custom run name (optional)'
        required: false

run-name: >
  ${{
    github.event_name == 'workflow_dispatch' && (
      inputs.run_title != '' && inputs.run_title
      || format('[RELEASE][TEST] {0}', github.event.head_commit.message)
    )
    || github.event_name == 'push' && format('{0}', github.event.head_commit.message)
  }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Next.js Project
        uses: ./.github/actions/setup-nextjs

  build-deploy-test:
    needs: setup
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Build and Deploy Test
        uses: ./.github/actions/build-and-deploy-nextjs
        with:
          stage: main
          service: corporate-travel-test-web
