name: Build and Deploy Staging

on:
  workflow_dispatch:

run-name: ${{ format('[RELEASE][STAGING] {0}', github.ref_name) }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Next.js Project
        uses: ./.github/actions/setup-nextjs

  build-deploy-staging:
    needs: setup
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Deploy Staging
        uses: ./.github/actions/build-and-deploy-nextjs
        with:
          stage: rc
          service: corporate-travel-staging-web
