name: PR Changelog Staging & Production

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - rc
      - release

jobs:
  generate-release-comment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set base and head branch for diff
        id: branch_info
        run: |
          echo "base=origin/${{ github.event.pull_request.base.ref }}" >> "$GITHUB_OUTPUT"
          echo "head=origin/${{ github.event.pull_request.head.ref }}" >> "$GITHUB_OUTPUT"

      - name: Extract Version from PR title
        id: release_version
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          VERSION=$(echo "$TITLE" | grep -oE 'v[0-9]+\.[0-9]+(-beta\.[0-9]+|-hotfix\.[0-9]+)?' || true)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Generate changelog (Node.js)
        run: |
          node ./scripts/versioning/generate-changelog.js \
          ${{ steps.branch_info.outputs.base }} ${{ steps.branch_info.outputs.head }} \
          pr-comment.md ${{ steps.release_version.outputs.version }} \

      - name: Add comment to PR
        uses: mshick/add-pr-comment@v2
        with:
          message-path: pr-comment.md
          allow-repeats: false